config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :unencrypted_token
    #before_create :save_token
    has_secure_password
    
  def User.new_token
    SecureRandom.urlsafe_base64.to_s
  end
  
  def User.encrypt(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def save_token
    self.unencrypted_token = User.new_token
    update_attribute(:remember_token, User.encrypt(unencrypted_token))
  end
  
  def forget
    update_attribute(:remember_token, nil)
  end
  
  def authenticated?(item)
    return false if remember_token.nil?
    BCrypt::Password.new(remember_token).is_password?(item)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]
  
  def index
  end
  
  def new
    @post = Post.new
  end
  
  def create
    all_params = post_params
    all_params[:user_id] = current_user.id
    @post = Post.new(all_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end
  
  private
  
    def post_params
      params.require(:post).permit(:title, :body)
    end
    
    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to(root_path)
    else
      render 'new'
    end
  end

  def destroy
    log_out 
    redirect_to(root_path)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    user.save_token
    cookies.permanent[:remember_token] = user.unencrypted_token
    cookies.permanent.signed[:user_id] = user.id
    @current_user = user
  end
  
  def current_user
    if (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    current_user.forget
    cookies.delete(:remember_token)
    cookies.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_header.html.erb
<% if logged_in? %>
Hello, <%= current_user.username %>!
<%= link_to "Log out", logout_path, method: "delete" %>
<%= link_to "Create a new post!", new_post_path %>
<% else %>
<%= link_to "Log in", login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>User Posts</h1>


<% Post.all.each do |post| %>
      <h3><%= post.title %></h3>
      <% post_author = User.find(post.user_id) %>
      <h4>By <%= logged_in? ? post_author.username : "Classified" %></h4>
      <p><%= post.body %></p>
      <br>
<% end %>

app/views/posts/new.html.erb
<h1>Create New Post</h1>

<%= form_for(@post) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit "Submit" %>
  
<% end %>